# Generated by Django 3.1.7 on 2021-03-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('expenses', '0002_auto_20210323_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.platformuser'),
        ),
        migrations.AlterField(
            model_name='expensedescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.platformuser'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.platformuser'),
        ),
    ]
